import marimo

__generated_with = "0.21.1"
app = marimo.App(width="full")


@app.cell
def _():
    import marimo as mo

    return (mo,)


@app.cell
def intro(mo):
    mo.md(r"""
    # 🤖 Welcome to the Google ADK Workshop

    In this interactive workshop, we're building **Production-Ready Intelligent Agents** natively on Vertex AI using the **Google Agent Development Kit (ADK)**.

    ### 🔑 System Terminology
    - **Agent**: The core LLM-powered entity. Configured with a `model`, an `instruction` prompt, and `tools`.
    - **Tool**: Standard Python functions (or endpoints) that let Agents execute real-world actions.
    - **Session**: The stateful memory structure that persists your agent's context across conversation turns.
    - **Event Stream**: The real-time deterministic output generated by agents (think `content` chunks, `tool_call` requests, and `grounding_metadata`).
    """)
    return


@app.cell
def mod1(mo):
    mo.md(r"""
    ---
    # Module 01: Foundation

    The defining building block of the ADK is the `Agent` class.
    You define the AI's persona, its capabilities, and let it run.

    Hit **Run** on the cell below to securely execute our first ADK Agent right here in the browser!
    """)
    return


@app.cell
def setup_runner():
    import os
    import asyncio
    from dotenv import load_dotenv
    from google.adk.agents import Agent, SequentialAgent, ParallelAgent
    from google.adk.runners import Runner
    from google.adk.sessions import InMemorySessionService
    from google.genai import types

    # Force Auth: Load local .env into environment
    load_dotenv("workspace/.env")
    os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "True"

    async def run_agent(agent, query: str, session_id: str = "slide-session"):
        session_svc = InMemorySessionService()
        runner = Runner(
            agent=agent, app_name="workshop_slides", session_service=session_svc
        )

        # Explicitly create the session before running
        await session_svc.create_session(
            app_name="workshop_slides", user_id="workshop", session_id=session_id
        )

        output = ""
        user_message = types.Content(role="user", parts=[types.Part(text=query)])
        async for event in runner.run_async(
            new_message=user_message, user_id="workshop", session_id=session_id
        ):
            if event.is_final_response() and event.content:
                for part in event.content.parts:
                    if part.text:
                        output += part.text
        return output

    return Agent, ParallelAgent, SequentialAgent, run_agent


@app.cell
def run_hello(Agent):
    # Define the foundational agent
    hello_agent = Agent(
        name="greeter",
        model="gemini-3-flash-preview",
        instruction="You are a warm, welcoming host for a Google Agent Development Workshop. You may use Markdown in your response.",
    )

    # result_text = await run_agent(hello_agent, "Hello, ADK!", session_id="hello-test")




    return (hello_agent,)


@app.cell
def _(mo):
    # Create the input fields and the run button
    agent_form = mo.ui.form(
        mo.vstack([
            mo.ui.text(label="User Query", value="Explain 3 things about Google Agent Development Kit (ADK)"),
        ]),
        label="Run Agent Configuration",
        submit_button_label="Run Agent"
    )

    # Display the form
    agent_form
    return (agent_form,)


@app.cell
async def _(agent_form, hello_agent, mo, run_agent):
    # This cell re-runs automatically when the user clicks 'Submit' in the form
    mo.stop(not agent_form.value, "Submit the form to see the result.")

    # Execute the agent
    _query = agent_form.value["User Query"]
    _result = await run_agent(hello_agent, _query, session_id="ui-test")

    # Render the result
    mo.md(f"### Agent Output:\n{_result}")
    return


@app.cell
def mod2(mo):
    mo.md(r"""
    ---
    # Module 02: Agent Orchestration

    Real-world AI systems rarely consist of just one mega-prompt. You need *Delegation*.

    ### Sequential Routing
    You can chain and group specialized agents together using `SequentialAgent`.
    This standard pattern routes a user's prompt through a strict order (e.g. `planner_agent` -> `researcher_agent` -> `writer_agent`), ensuring tightly controlled state transfer.
    """)
    return


@app.cell
async def run_sequential(Agent, SequentialAgent, run_agent):
    researcher = Agent(
        name="researcher",
        model="gemini-3-flash-preview",
        instruction="State 1 interesting historical fact about artificial intelligence. Be brief.",
    )

    writer = Agent(
        name="writer",
        model="gemini-3-flash-preview",
        instruction="Rewrite the provided fact into a catchy, 5-word news headline.",
    )

    seq_pipeline = SequentialAgent(name="seq_pipeline", sub_agents=[researcher, writer])

    seq_result = await run_agent(
        seq_pipeline, "Tell me an AI fact.", session_id="seq-test"
    )
    return


@app.cell
def display_seq():
    return


@app.cell
def mod3(mo):
    mo.md(r"""
    ---
    # Module 03: Advanced Orchestration

    Why wait sequentially when you can process an entire newspaper concurrently?

    ### Parallel Execution Networks
    By grouping agents inside a `ParallelAgent`, the ADK will automatically fan-out and spin up identical sub-agents (or wildly different sub-agents) to execute independent work at the exact same time.

    *This is exactly how our News Harvester compiled 100+ articles in seconds!*
    """)
    return


@app.cell
async def run_parallel(Agent, ParallelAgent, run_agent):
    analyst_pro = Agent(
        name="analyst_pro",
        model="gemini-3-flash-preview",
        instruction="In exactly one sentence, describe the biggest benefit of AI.",
    )

    analyst_con = Agent(
        name="analyst_con",
        model="gemini-3-flash-preview",
        instruction="In exactly one sentence, describe the biggest risk of AI.",
    )

    para_pipeline = ParallelAgent(
        name="para_pipeline", sub_agents=[analyst_pro, analyst_con]
    )

    para_result = await run_agent(
        para_pipeline, "Analyze AI tradeoffs.", session_id="para-test"
    )
    return


@app.cell
def display_para():
    return


if __name__ == "__main__":
    app.run()
